apiVersion: v1
kind: ConfigMap
metadata:
  name: datasource
data:
  application.properties: |-
    # Oracle settings-CLI
    spring.datasource.url = jdbc:mysql://mysql-svc:3306/samstore?useSSL=false
    spring.datasource.username = root
    spring.datasource.password = root1234
    spring.datasource.driver-class-name=com.mysql.jdbc.Driver
    spring.jpa.database-platform=org.hibernate.dialect.Oracle10gDialect
    # HikariCP settings
    # spring.datasource.hikari.*
    mybatis.mapper-locations=mybatis/**/*.xml
    server.port=8080
    environment.data.path=classpath:data.json
    #logging configuraion
    logging.config=classpath:logback.xml
    spring.datasource.hikari.connection-timeout=60000
    spring.datasource.hikari.maximum-pool-size=5